const data =[
  "Memory (GB)",
  "Memory Hours US East (GB)",
  "Memory Hours US West (GB)",
  "Data Transferred US East (GB)",
  "Data Transferred Hours US East (GB)",
  "Data Transferred Hours US West (GB)",
  "Data Transferred US West (GB)",
  "VM Disk Size (GB)",
  "VM Disk Size Hours US East (GB)",
  "VM Disk Size Hours US West (GB)",
  "CPU (GHz)",
  "CPU Hours US East (GHz)",
  "CPU Hours US West (GHz)",
  "IP Public Hours",
  "IP Hours",
  "IP Hours US East",
  "IP Hours US West",
  "Windows license fee",
  "Windows license fee US East",
  "Windows license fee US West",
  "CPU Hours US East",
  "CPU Hours US West",
  "Memory (GB)",
  "Memory Hours US East (GB)",
  "Memory Hours US West (GB)",
  "Replicated VMs/Month",
  "No of Replicated VMs US East",
  "No of Replicated VMs US West",
  "Data Encryption",
  "Data Encryption US East",
  "Data Encryption US West",
  "VPN Connection",
  "VPN Connection Hours US East",
  "VPN Connection Hours US West",
  "VPN Setup Fee",
  "VPN Setup Fee US East",
  "VPN Setup Fee US West",
]
